# -*- coding: utf-8 -*-
"""CodeAlpha_Task2_Unemployment_Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uo_2apX3kxmj3_9gSQNhjt13Gme51Wvz

# **Unemployment Analysis in India using Python**

### **CodeAlpha Data Science Internship - Task 2**

**Intern Name:** Radhika

**Platform:** Google Colab

**Programming Language:** Python


## 📌 Project Objective

This project aims to analyze unemployment trends across different states of India using Python.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""## Step 1: Upload and Load Dataset

The unemployment dataset is uploaded and loaded into a Pandas DataFrame for analysis.
"""

from google.colab import files

uploaded = files.upload()

data = pd.read_csv("Unemployment in India.csv")

"""## Step 2: Exploratory Data Analysis (EDA)

The dataset structure, missing values, and summary statistics are examined.
"""

data.head()

data.info()

"""# Dataset Information

The dataset information displays the number of records, column names, data types, and non-null values present in each column.
"""

data.describe()

"""# Statistical Summary

The statistical summary provides measures such as mean, standard deviation, minimum, maximum, and quartile values for numerical variables.
"""

data.isnull().sum()

"""# Missing Value Analysis

The dataset contains some missing values that need to be handled before performing further analysis and visualization.

## Step 3: Data Cleaning

Missing values are identified and handled to prepare the dataset for analysis.
"""

data = data.dropna()
data.isnull().sum()

"""# Data Cleaning Result

After removing missing values, the dataset contains no null values and is ready for analysis.*italicized text*
"""

data.shape

data.columns

print(data.columns.tolist())

"""# Dataset Structure
Total Rows: 740
Total Columns: 7
Column names were verified successfully.
Dataset structure is suitable for visualization and analysis.

# Step 4: Data Visualization and Analysis

This section explores unemployment trends, labour participation rates, employment levels, and regional differences using graphical visualizations.
"""

top_states = data.groupby('Region')[' Estimated Unemployment Rate (%)'].mean().sort_values(ascending=False)

plt.figure(figsize=(12,6))
top_states.head(10).plot(kind='bar')
plt.title('Top 10 States with Highest Unemployment Rate')
plt.ylabel('Unemployment Rate (%)')
plt.show()

"""### Top 10 States with Highest Unemployment Rate

This visualization highlights the states with the highest average unemployment rates in India.
"""

plt.figure(figsize=(8,5))
sns.boxplot(x='Area', y=' Estimated Unemployment Rate (%)', data=data)
plt.title('Rural vs Urban Unemployment')
plt.show()

"""# Rural vs Urban Unemployment Comparison

The boxplot compares unemployment levels between rural and urban areas, helping to understand regional employment differences.
"""

numeric_data = data.select_dtypes(include=['float64','int64'])

plt.figure(figsize=(8,5))
sns.heatmap(numeric_data.corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

"""# Correlation Analysis

The heatmap shows relationships among unemployment rate, employment level, and labour participation rate. Stronger correlations indicate closer relationships between variables.
"""

data[' Date'] = pd.to_datetime(data[' Date'])

monthly = data.groupby(data[' Date'].dt.month)[' Estimated Unemployment Rate (%)'].mean()

plt.figure(figsize=(10,5))
monthly.plot(marker='o')
plt.title("Average Monthly Unemployment Trend")
plt.xlabel("Month")
plt.ylabel("Unemployment Rate (%)")
plt.grid(True)
plt.show()

"""# Monthly Unemployment Trend

This line chart illustrates how unemployment rates change over different months and helps identify seasonal trends.
"""

top_labour = data.groupby('Region')[' Estimated Labour Participation Rate (%)'].mean().sort_values(ascending=False).head(10)

plt.figure(figsize=(10,5))
top_labour.plot(kind='bar')
plt.title("Top 10 States by Labour Participation Rate")
plt.ylabel("Labour Participation Rate (%)")
plt.xticks(rotation=45)
plt.show()

"""# Labour Participation Analysis

This visualization identifies the states with the highest labour participation rates, indicating greater workforce involvement.
"""

plt.figure(figsize=(8,5))
sns.histplot(data[' Estimated Unemployment Rate (%)'], bins=20, kde=True)

plt.title("Distribution of Unemployment Rate")
plt.xlabel("Unemployment Rate (%)")
plt.ylabel("Frequency")

plt.show()

"""# Distribution of Unemployment Rate

The histogram displays how unemployment rates are distributed across observations and reveals the overall pattern of unemployment.
"""

top_emp = data.groupby('Region')[' Estimated Employed'].mean().sort_values(ascending=False).head(10)

plt.figure(figsize=(10,5))
top_emp.plot(kind='bar')
plt.title('Top 10 States by Employment')
plt.ylabel('Estimated Employed')
plt.xticks(rotation=45)
plt.show()

"""# Employment Distribution by State

This chart highlights states with the highest employment levels and provides insights into workforce concentration.
"""

plt.figure(figsize=(8,5))
sns.scatterplot(
    x=' Estimated Labour Participation Rate (%)',
    y=' Estimated Unemployment Rate (%)',
    data=data
)

plt.title('Labour Participation vs Unemployment')
plt.show()

"""# Labour Participation vs Unemployment

The scatter plot helps examine the relationship between labour participation and unemployment rates across observations.
"""

region_avg = data.groupby('Region')[' Estimated Unemployment Rate (%)'].mean().sort_values(ascending=False)

plt.figure(figsize=(12,5))
region_avg.plot(kind='bar')
plt.title('Average Unemployment Rate by State')
plt.ylabel('Unemployment Rate (%)')
plt.xticks(rotation=90)
plt.show()

"""# Final Conclusion
Significant variations in unemployment rates exist across Indian states.
Labour participation rates differ among regions, indicating workforce diversity.
Rural and urban areas show different unemployment characteristics.
Employment levels and unemployment rates are influenced by regional economic conditions.
Data visualization helped identify important trends and patterns within the dataset.
"""