# -*- coding: utf-8 -*-
"""CodeAlpha_Task1_Iris_Flower_Classification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KM9jBYtqen8JOIahuUMQyVwW0AzVHYSA

# **Iris Flower Classification**

### **CodeAlpha Data Science Internship - Task 1**

**Intern Name:** Radhika

**Platform:** Google Colab

**Programming Language:** Machine Learning


## 📌 Project Objective

The objective of this project is to classify Iris flowers into different species based on their sepal and petal measurements using Machine Learning techniques.

## Step 1: Import Required Libraries

The required Python libraries are imported for data manipulation, visualization, machine learning model development, and evaluation.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

"""## Step 2: Load the Iris Dataset

The Iris dataset is loaded from the Scikit-learn library and converted into a Pandas DataFrame for analysis.
"""

# Load Dataset

iris = load_iris()

df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

df["species"] = iris.target

df.head()

"""## Step 3: Dataset Overview

The first few records of the dataset are displayed to understand the structure, features, and target labels.
"""

df["species"] = df["species"].map({
    0: "Setosa",
    1: "Versicolor",
    2: "Virginica"
})

df.head()

"""## Step 4: Data Exploration

The dataset is explored using descriptive statistics and information summaries to understand feature distributions and data quality.
"""

df.info()

df.describe()

df.isnull().sum()

df["species"].value_counts()

"""## Species Distribution Analysis

A count plot is used to visualize the distribution of Iris flower species in the dataset.
"""

# Count Plot

plt.figure(figsize=(6,4))

sns.countplot(x="species", data=df)

plt.title("Count of Iris Flower Species")
plt.xlabel("Species")
plt.ylabel("Count")

plt.show()

"""## Pairwise Feature Analysis

A pair plot is generated to visualize relationships between features and identify patterns among different Iris species.
"""

# Pair Plot

sns.pairplot(df, hue="species")

plt.show()

"""## Correlation Analysis

A correlation heatmap is used to identify relationships between numerical features and understand feature dependencies.
"""

# Correlation Heatmap

plt.figure(figsize=(8,6))

sns.heatmap(
    df.drop("species", axis=1).corr(),
    annot=True,
    cmap="Blues"
)

plt.title("Correlation Heatmap")

plt.show()

"""## Feature Selection

The input features are selected as independent variables, while the species column is selected as the target variable.
"""

# Features and Target

X = df.drop("species", axis=1)

y = df["species"]

"""## Train-Test Split

The dataset is divided into training and testing sets to evaluate the performance of the machine learning model on unseen data.
"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

"""## Model Training

A Decision Tree Classifier is trained using the training dataset to learn patterns and classify Iris flower species.
"""

model = DecisionTreeClassifier(random_state=42)

model.fit(X_train, y_train)

"""## Model Prediction

The trained model is used to predict flower species for the testing dataset.
"""

y_pred = model.predict(X_test)

"""## Model Evaluation

The performance of the model is evaluated using Accuracy Score, Classification Report, and Confusion Matrix.
"""

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,4))

sns.heatmap(
    cm,
    annot=True,
    cmap="Blues",
    fmt="d",
    xticklabels=model.classes_,
    yticklabels=model.classes_
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")

plt.show()

"""## Testing with New Sample Data

The trained model is tested using new flower measurements to predict the corresponding Iris species.
"""

sample = [[5.1, 3.5, 1.4, 0.2]]

prediction = model.predict(sample)

print("Predicted Species:", prediction[0])

"""## Model Saving

The trained machine learning model is saved for future use and deployment.
"""

import joblib

joblib.dump(model, "iris_model.pkl")

print("Model Saved Successfully")

print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, cmap="Blues", fmt="d",
            xticklabels=model.classes_,
            yticklabels=model.classes_)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

sample = [[5.1, 3.5, 1.4, 0.2]]

prediction = model.predict(sample)

print("Predicted Species:", prediction[0])

"""# 📌 Conclusion

The Iris Flower Classification model was successfully developed using Machine Learning techniques.

The Decision Tree Classifier achieved excellent classification performance and accurately identified Iris flower species based on sepal and petal measurements.

The project demonstrates the effectiveness of machine learning in solving multiclass classification problems and highlights the importance of feature analysis and model evaluation.
"""